Add filterfalse to itertools
maxfischer2781/asyncstdlib pull request #109
Opened 2023-04-27 08:09 UTC by ziima

2023-05-01 07:33 UTC, maxfischer2781 commented
Thanks for the contribution and especially for spotting that this was missing!

2023-05-01 07:40 UTC, maxfischer2781 requested changes
This looks overall good to go. Please take a look at the failed "Static Checks" and adjust the code accordingly.

Feel free to disregard the codecov failure. I'll leave it up to you whether you want to address the CodeQL report, I'm fine with both variants.

* [x] Static Checks must succeed
* [x] Consider to address the CodeQL report

2023-05-05 15:31 UTC, ziima commented on unittests/test_itertools.py
> +    (lambda x: bool(x), [0, 1] * 5),
Fixed.

2023-05-05 15:33 UTC, ziima commented
>     * [ ]  Static Checks must succeed
>     * [ ]  Consider to address the CodeQL report

Both should be fixed now.

2023-05-07 06:08 UTC, maxfischer2781 approved these changes
Looks good to go!

2023-05-07 06:35 UTC, merged