Add itertools batched
maxfischer2781/asyncstdlib pull request #115
Opened 2023-12-18 09:41 UTC by ziima

Add async version of `itertools.batched`.

2023-12-30 13:01 UTC, maxfischer2781 requested changes
Please use the abstractions from `_core`, I've added comments on how to use them.

2023-12-30 13:01 UTC, maxfischer2781 commented on asyncstdlib/itertools.py
> +    Batch the ``iterable`` to the tuples of the length ``n``.
```suggestion
    Batch the ``iterable`` to tuples of the length ``n``.
```

2024-01-04 08:48 UTC, ziima commented
Updated.

2024-01-05 10:08 UTC, maxfischer2781 approved these changes
Looks good to go. Thanks for the contribution and taking your time to handle feedback. :+1:

2024-01-05 10:09 UTC, merged