Fix tests stubs
maxfischer2781/asyncstdlib pull request #140
Opened 2024-04-03 15:06 UTC by isra17

The current typing yield the following error:

```
error: "Coroutine[Any, Any, AsyncIterator[Any]]" has no attribute "__aiter__" (not async iterable)  [attr-defined]
```

Related to https://github.com/python/mypy/issues/10301

I also took time to add a typing test for every function in itertools that validate the iterator type. I added a dependency to `mypy-type-assets` to easily assert the type.

2024-04-04 07:27 UTC, maxfischer2781 commented
Good catch. I'll try and review this ASAP.

2024-04-04 07:30 UTC, maxfischer2781 commented
As a first glance, can you switch from the MyPy assertion plugin to using [`typing.assert_type`](https://docs.python.org/3/library/typing.html#typing.assert_type) (import it from `typing_extensions`)? The type checks should also work for PyRight, so a general means is preferable.

2024-04-04 14:03 UTC, isra17 commented
> As a first glance, can you switch from the MyPy assertion plugin to using [`typing.assert_type`](https://docs.python.org/3/library/typing.html#typing.assert_type) (import it from `typing_extensions`)? The type checks should also work for PyRight, so a general means is preferable.

I wasn't aware of this new function, done!

2024-04-08 07:10 UTC, maxfischer2781 requested changes
Looks good. The only thing left to do is cleanup of unused dependencies.

2024-04-08 07:10 UTC, maxfischer2781 commented on pyproject.toml
> +    "mypy-typing-asserts",
Please also remove the dependency now that it is not used.
```suggestion
```

2024-04-08 07:10 UTC, maxfischer2781 commented on pyproject.toml
> +plugins = ["mypy_typing_asserts.mypy_plugin"]
See previous comment.
```suggestion
```

2024-04-08 07:10 UTC, maxfischer2781 commented on typetests/test_itertools.py
> +from typing import AsyncIterator
```suggestion
```

2024-04-09 19:56 UTC, isra17 commented
> Looks good. The only thing left to do is cleanup of unused dependencies.

Sorry, forgot to clean up, done

2024-04-09 20:31 UTC, isra17 commented on typetests/test_itertools.py
> +from typing import AsyncIterator
It's actually required. Seems like the code scanner is unable to figure out usage through string types.

2024-04-11 08:23 UTC, maxfischer2781 approved these changes
This is good to go. Thanks for spotting this issue and your contribution! 👍

2024-04-11 08:34 UTC, merged