Add `apply` to `asynctools`
maxfischer2781/asyncstdlib pull request #34
Opened 2021-02-23 15:17 UTC by mristin

* Add `apply` to `asynctools` module

* Document `apply`

* Fixes the issue #33.

2021-02-23 15:18 UTC, mristin commented
@maxfischer2781 I need to rebase this pull request after we merge in the pull request #33, but you can already give it a first pass and review it.

2021-02-23 17:00 UTC, maxfischer2781 requested changes
I recommend changing the function argument name to avoid collisions.

Do you feel a fast-path is required? Say, if ``kwargs`` are empty?

2021-02-23 17:00 UTC, maxfischer2781 commented on docs/source/api/asynctools.rst
> +    :async:
```suggestion
.. autofunction:: apply(func: (*T, **T) -> R, *args: await T, **kwargs: await T) -> R
    :async:
```

2021-02-23 17:00 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +    func: Callable[..., T], *args: Awaitable[Any], **kwargs: Awaitable[Any]
Allow using ``func`` as a keyword.
```suggestion
    __func: Callable[..., T], *args: Awaitable[Any], **kwargs: Awaitable[Any]
```

2021-02-23 17:00 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +    return func(
```suggestion
    return __func(
```

2021-02-23 19:54 UTC, mristin commented
> Do you feel a fast-path is required? Say, if `kwargs` are empty?

I am not familiar with the concept of *fast-path* -- you mean checking if `kwargs` are empty and branching accordingly?

2021-02-24 12:28 UTC, mristin commented
@maxfischer2781 The pull request is ready for review (and merge, if all's good).

2021-02-24 16:53 UTC, maxfischer2781 approved these changes
Looks good to me. Many thanks for the contribution.

2021-02-24 16:57 UTC, merged