Add asynctools.make_awaitable
maxfischer2781/asyncstdlib pull request #46
Opened 2021-06-22 15:18 UTC by ArtyomKozyrev8

Implemented the feature described in [Issue-42](https://github.com/maxfischer2781/asyncstdlib/issues/42)
Please check and advise.

2021-06-26 13:24 UTC, maxfischer2781 requested changes
Looks pretty good! Good thinking with the addition of the ``Callable`` check, that indeed looks like a worthwhile protection against misuse.

I've added comments on some things I would like to see changed. The PR is good to go if you address them.

2021-06-26 13:24 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +def make_awaitable(function: Callable[..., T]) -> Callable[..., Awaitable[T]]:
Had to ponder the name a bit. I feel that this shorter one is more suitable:
```suggestion
def sync(function: Callable[..., T]) -> Callable[..., Awaitable[T]]:
```
This matches the naming scheme of relying on ``import asyncstdlib as a`` – so it gives the name ``a.sync`` in practice.

2021-06-26 13:24 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +            ...
Please remove that example. It's valid but I'm afraid it might lead people to cargo-cult this pattern.

2021-06-26 13:24 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +            await test2_async(x=7)
When removing ``test2_async`` above, consider to show a case that uses a ``lambda`` here. For example:
```suggestion
            await a.sync(lambda x: x)(42)
```

2021-06-26 13:24 UTC, maxfischer2781 commented on asyncstdlib/asynctools.py
> +
Please add a fast path for native coroutines here. (``iscoroutinefunction`` comes from ``inspect``)
https://github.com/maxfischer2781/asyncstdlib/blob/b48fb6363b2110c72cfd012fea84b399c6b2aab9/asyncstdlib/_core.py#L91-L92
A primary use-case for this helper is to force some input function to be awaitable, no matter whether it was before. But often enough the input already is a proper, fast coroutine and wrapping it only makes things slower.

2021-06-26 19:13 UTC, ArtyomKozyrev8 commented
> Looks pretty good! Good thinking with the addition of the `Callable` check, that indeed looks like a worthwhile protection against misuse.
> 
> I've added comments on some things I would like to see changed. The PR is good to go if you address them.

@maxfischer2781 thanks, I've made the requested changes, please check

2021-06-27 10:09 UTC, maxfischer2781 approved these changes
That looks good to go! Thanks a lot for your contribution. 👍

2021-06-27 10:39 UTC, merged

2021-06-27 10:40 UTC, ArtyomKozyrev8 commented
> That looks good to go! Thanks a lot for your contribution. 👍

@maxfischer2781 nice to hear it, let me know if there are any other simple tasks I can solve and contribute to the project